### ISSUE TITLE
Huge Memory usage

### ISSUE THREAD

**Issue by pietropau** [GridProtectionAlliance/openHistorian#11]
When you set e new internal subscriber in opehhistorian (version 2.0.347.0) require high memory usage.

![openhistorian_ram](https://cloud.githubusercontent.com/assets/18598157/16594031/a4e9e32a-42e8-11e6-8733-a2b2fbbd712e.JPG)

Thanks,
Pietro

**Comment by ritchiecarroll** [comment]
How large of a data set are you subscribing to? For example, how many metadata points exist in the openPDC?

**Comment by pietropau** [comment]
Openpdc is connected up 216 PMU (200 Voltage, 600 Currents).

Pietro

**Comment by StephenCWills** [comment]
I wasn't able to reproduce the issue. Can we get the hardware specs of the system running the openHistorian? Also, do you know about how long the openHistorian was running before you took the screenshot?

**Comment by pietropau** [comment]
Hardware specs: Dual-core Opteron 2.40 Hz with 8 GB RAM. 
About memory, it takes two minutes for reach 8 Gb

**Comment by pietropau** [comment]
- I reset Openpdc and openhistorian configuration with "configuration setup utility"
- Openpdc configured with 1 PDC with 18 PMU and for receive internal metadata
- Openhistorian configured for receive external metadata from Openpdc

![openhistorian](https://cloud.githubusercontent.com/assets/18598157/16613168/1959be56-436b-11e6-86f4-290c2d5d5c83.JPG)

**Comment by ritchiecarroll** [comment]
I guess the best thing we can do at this stage since we are not able to replicate your issue is to get a fresh copy of your log files at system start-up. To do this, stop the openHistorian service and delete (or rename) the following files: StatusLog.txt and ErrorLog.txt. Then restart the openHistorian and send us a copy of these log files a after few minutes. This may help us diagnose the issue you are seeing.

**Comment by StevenChisholm** [comment]
The openHistorian was originally designed to have a huge memory buffer for the archive files. After using it in production at OG&E, I've determined that Microsoft since Windows 2008 R2 does a decent job caching the files under the surface as long as they stay open. I'm in the process of reworking how aggressive the historian is at caching files. In the mean time, you can edit your application settings. This can be done by changing "MemoryPoolSize" under the "SystemSettings" in the "openHistorian.exe.config" file to something smaller. I think the value is in GB.

**Comment by pietropau** [comment]
Now it's openpdc that require huge memory.

![openpdc](https://cloud.githubusercontent.com/assets/18598157/16681325/4b12e1ea-44f4-11e6-9820-d2b116caa76a.JPG)

In my opinion there exists a trouble in the configuration for internal connection between your openPDC and open Historian. Are configured both for receive internal/external metada? is it correct ?

Thanks
Pietro

**Comment by ritchiecarroll** [comment]
Can we get a copy of your log files?

**Comment by pietropau** [comment]
[Health.txt](https://github.com/GridProtectionAlliance/openHistorian/files/353891/Health.txt)
[StatusLog.txt](https://github.com/GridProtectionAlliance/openHistorian/files/353893/StatusLog.txt)
[ErrorLog.txt](https://github.com/GridProtectionAlliance/openHistorian/files/353892/ErrorLog.txt)

**Comment by ritchiecarroll** [comment]
Note that these logs look to be for the historian. Since the openPDC is the one with a large memory pool, can we get those logs. Note that it would also be helpful to see your Status.txt as well - this file is only logged every thirty minutes, but it shows detailed status of all system adapters.

In the historian logs you provided I did seeing some errors, e.g.: 

Failure code received in response to server command "MetaDataRefresh": Failed to transfer meta-data due to exception: Failed to open ADO data connection, verify "ConnectionString" in configuration file: Authentication to host 'localhost' for user 'root' using method 'mysql_native_password' failed with message: Reading from the stream has failed.

Failed to transfer meta-data due to exception: Failed to open ADO data connection, verify "ConnectionString" in configuration file: Authentication to host 'localhost' for user 'root' using method 'mysql_native_password' failed with message: Reading from the stream has failed.

---

However, it looks the system may have recovered from these issues.

Also, are you running on a Virtual Machine?

Thanks,
Ritchie

**Comment by ritchiecarroll** [comment]
In the logs you have an IEEE C37.118 PDC style connection called PDC12 and a GEP style subscription called HIS. Can you provide a drawing of your configuration? Here is how I would recommend configuration on this system (based on my current understanding):

![recommended architecture](https://cloud.githubusercontent.com/assets/9202752/16687216/2ba28c0c-44e5-11e6-9eac-d2d09c2d23ad.png)

**Comment by StephenCWills** [comment]
Hi Pietro,

I think Ritchie has the right idea with the architecture diagram. I see a lot of messages in StatusLog.txt about out-of-sequence statistic measurements. Not only is it a highly unusual message, but it seems to be repeating the same IDs and timestamps while the count of out-of-sequence measurements continuously increases. This suggests you may have a data feedback loop, and that would also explain the memory usage going out of control.

It may be easiest to start over from scratch, making your connections according to the suggested architecture diagram posted by Ritchie.

Thanks,
Stephen

**Comment by pietropau** [comment]
We are trying to apply the architecture suggested,  starting over from scratch.
The files provided are from openpdc folder. 
The server is not virtual machine
I change PDC wit single PMU for test.

[StatusLog.txt](https://github.com/GridProtectionAlliance/openHistorian/files/354499/StatusLog.txt)

**Comment by pietropau** [comment]
First test

1)  I start over from scratch openpdc and openhistorian, I have configured one PMU into openPDC

![1](https://cloud.githubusercontent.com/assets/18598157/16734433/cbfb0844-4785-11e6-86e7-ace0242c72d9.JPG)

2) Openpdc configured for receive internal/external metadata 

![2](https://cloud.githubusercontent.com/assets/18598157/16734471/f1c47e52-4785-11e6-8eab-03065df18e4b.JPG)
![3](https://cloud.githubusercontent.com/assets/18598157/16734483/f95b7c24-4785-11e6-8dcc-0c17333bb8fb.JPG)

3) Memory required by openpdc increasing 

![4](https://cloud.githubusercontent.com/assets/18598157/16734535/327889fc-4786-11e6-9f94-ec852d6cb084.JPG)
![5](https://cloud.githubusercontent.com/assets/18598157/16734544/3a277064-4786-11e6-8ab6-998749331976.JPG)



 Second Test

1)  I start over from scratch openpdc and openhistorian, I have configured one PMU into openPDC

![1](https://cloud.githubusercontent.com/assets/18598157/16734433/cbfb0844-4785-11e6-86e7-ace0242c72d9.JPG)

2) Openhistorian configured for receive internal metadata 

![8](https://cloud.githubusercontent.com/assets/18598157/16734601/6e8d7ca4-4786-11e6-8b30-93ea591c81ee.JPG)

3) Memory required by openpdc increasing 

![9](https://cloud.githubusercontent.com/assets/18598157/16734611/75397878-4786-11e6-9f93-bb60fa759e5c.JPG)

**Comment by ritchiecarroll** [comment]
This is a miss configuration - so sorry for the confusion. The configuration listed is creating a feed-back loop. I will try to detail the steps:

**Comment by ritchiecarroll** [comment]
1. From openPDC: Connect to PMU
2. From openHistorian: Connect to openPDC, steps are as follows
  * Select "Inputs / Subscription Based Inputs / Create Internal Subscription":
![image](https://cloud.githubusercontent.com/assets/9202752/16734975/5c3505ee-4755-11e6-8159-bbfc7caf9f55.png)
  * Fill out info *CRITICAL* - set port to ***6165*** for openPDC:
![image](https://cloud.githubusercontent.com/assets/9202752/16735101/d4ef3b6c-4755-11e6-838d-ddaccb0f022a.png)

That should correct issue - note that you may need to re-rerun Configuration Setup Utility for openHistorian and create a new database. Also: With openHisorian service stopped, I would recommend deleting current "C":\Program Files\openHistorian\Archive" folder to clear out current data.

**Comment by pietropau** [comment]
Ok now it's working, thanks

**Comment by ritchiecarroll** [comment]
Excellent!!
