### ISSUE TITLE
Is there any mechanism to store Historian Data directly into any RDBMS like Oracle/SQL Server instead of Files

### ISSUE THREAD

**Issue by ankitshah-it** [GridProtectionAlliance/openHistorian#49]
Dear All, 
As i must store data into RDBMS Oracle or SQL Server, So can we store the Data which we are storing into the Files instead can we store directly (not import-export) Oracle or SQL Server Database. If yes then how it is possible if no what are the limitations.
Thanks in Advance

**Comment by ritchiecarroll** [comment]
You can use the ADO output adapter for this exact purpose. However, there are real limitations on the volume of data you can archive into a database. If you are looking to archive synchrophasor data, you will be limited to a small set of devices.

**Comment by ritchiecarroll** [comment]
@ankitshah-it  - since this is not technically an issue with openHistorian I am going to close this ticket.
Note that we have a discussion board where you can ask general questions and search for previously answers, see here:

https://discussions.gridprotectionalliance.org/c/gpa-products/openhistorian

Thanks!
Ritchie

**Comment by ankitshah-it** [comment]
Thanks
