### ISSUE TITLE
Grafana and OH User Synchronization requires log-on 

### ISSUE THREAD

**Issue by clackner-gpa** [GridProtectionAlliance/openHistorian#53]
Adding a user to the OH and running /grafana/synchUsers won't result in the user being synchronized to Grafana. 

![image](https://user-images.githubusercontent.com/52460212/72385228-00fdbf00-36ed-11ea-9355-9cde020e5539.png)

However if the user account logs into Grafana for the first time it will automatically be synched from the OH.

**Comment by ritchiecarroll** [comment]
I first suspected this may have been related to a user having no roles, but currently unless a user actually logs in to openHistorian, they won't be synchronized to Grafana. This seems logical enough, but makes assigning rights in Grafana a process that can't be completed without user logging in. Perhaps an additional flag to the `syncusers` command to force synchronization would be sufficient since this is an edge case.

**Comment by ritchiecarroll** [comment]
Fixed #5fb584f16beef4263f3188983cd81d88d5497b6e
