### ISSUE TITLE
Trend/Export Measurements Timestamps

### ISSUE THREAD

**Issue by RenosKo** [GridProtectionAlliance/openHistorian#54]
Hello everyone!
I am currently working on a project that i have connected a PMU device to a local openHistorian instance and it seems that i need your help on this. On the Trend/Export Measurements via OpenHistorian WebUI i am able to declare a start/stop time with mm/yy hr:min:secs.ms but when i export the csv file it the timestamp column is displayed in seconds and not in ms. 
So i replaced the format manualy as " d/m/yyyy hh:mm:ss.000".
Is there a way to modify the csv to be exported to have this format initially and not have to and change it manually every time i need to extract data?
It might be something silly but i can't seem to find it anywhere.

**Comment by StephenCWills** [comment]
Hello RenosKo,

I believe Excel uses the regional settings in Windows to determine what the default date format should be when formatting a date column. It's not possible to provide formatting data to Excel in a CSV file, and I haven't found any particularly good workarounds or solutions. As this is more a problem with Excel rather than openHistorian, I am closing this issue.

Thanks,
Stephen
