### ISSUE TITLE
Output Streams

### ISSUE THREAD

**Issue by pietropau** [GridProtectionAlliance/openHistorian#8]
why openhistorian 2.0.347 does not handle "concentrator output streams" ?

**Comment by ritchiecarroll** [comment]
Technically it can - it just not listed on the Menu since we didn't think it would be commonly used in the historian.

You can easily modify Menu.xml in the C:\Program Files\openHistorian\ installation folder and add the concentrator output item back to the menu:

`      <MenuDataItem Icon="" MenuText="_Concentrator Output Streams" Description="Manage Output Streams" Roles="*" UserControlAssembly="GSF.PhasorProtocols.UI.WPF.dll" UserControlPath="GSF.PhasorProtocols.UI.UserControls.OutputStreamUserControl" />
`

**Comment by ritchiecarroll** [comment]
Please move product questions to discussion board: http://discussions.gridprotectionalliance.org/c/gpa-products/openhistorian
